# Generated by Django 4.2.13 on 2024-06-23 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees_payment_app', '0002_fee_student_payment_date_created_payment_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fee',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='course',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='student',
        ),
        migrations.AddField(
            model_name='fee',
            name='date_created',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='date_updated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='level',
            field=models.CharField(choices=[('Level 100', 'Level 100'), ('Level 200', 'Level 200'), ('Level 300', 'Level 300'), ('Level 400', 'Level 400')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='percentage',
            field=models.CharField(choices=[('100%', '100%'), ('50%', '50%')], default='100%', max_length=10),
        ),
        migrations.AddField(
            model_name='fee',
            name='student_category',
            field=models.CharField(choices=[('Freshmen', 'Freshmen'), ('Top-up', 'Top-up'), ('Continuing', 'Continuing')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='tuition_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='completion_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_level',
            field=models.CharField(choices=[('Level 100', 'Level 100'), ('Level 200', 'Level 200'), ('Level 300', 'Level 300'), ('Level 400', 'Level 400')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_updated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='entry_level',
            field=models.CharField(choices=[('Level 100', 'Level 100'), ('Level 200', 'Level 200'), ('Level 300', 'Level 300'), ('Level 400', 'Level 400')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Ghanaian', 'Ghanaian'), ('International Student', 'International Student')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_category',
            field=models.CharField(choices=[('Freshmen', 'Freshmen'), ('Top-up', 'Top-up'), ('Continuing', 'Continuing')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fees_payment_app.fee'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.AddField(
            model_name='fee',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fees_payment_app.academic_year'),
        ),
        migrations.AddField(
            model_name='fee',
            name='facaulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fees_payment_app.faculty'),
        ),
        migrations.AddField(
            model_name='student',
            name='facaulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees_payment_app.faculty'),
        ),
    ]
