# Generated by Django 4.2.13 on 2024-06-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_payment_app', '0003_academic_year_faculty_studentcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
