# Generated by Django 4.2.13 on 2024-06-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_payment_app', '0004_fee_total_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='nationality',
            field=models.CharField(choices=[('Ghanaian', 'Ghanaian'), ('International Student', 'International Student')], max_length=255, null=True),
        ),
    ]
