# Generated by Django 4.2.13 on 2024-06-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees_payment_app', '0006_fee_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_year',
            name='year',
            field=models.CharField(choices=[(2024, 2024), (2023, 2023), (2022, 2022), (2021, 2021)], max_length=4),
        ),
        migrations.CreateModel(
            name='Student_Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_created', models.DateField(auto_now=True, null=True)),
                ('date_updated', models.DateField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees_payment_app.student')),
            ],
        ),
    ]
