# Generated by Django 4.2.13 on 2024-07-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees_payment_app', '0009_rename_full_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty',
            new_name='Facaulty',
        ),
    ]
