# Generated by Django 4.2.13 on 2024-07-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees_payment_app', '0010_rename_faculty_facaulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_year',
            name='year',
            field=models.CharField(choices=[(2024, 2024), (2023, 2023), (2022, 2022), (2021, 2021)], max_length=20),
        ),
    ]
