# Generated by Django 4.2.13 on 2024-07-06 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees_payment_app', '0011_alter_academic_year_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_year',
            name='year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees_payment_app.academic_year'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='other_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fees_payment_app.student'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='tuition_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
